### ISSUE TITLE
我想加入OpenMinecraftMirror

### ISSUE THREAD

**Issue by RaymondChang1204** [XGHeaven/mcm#1]
我想加入OpenMinecraftMirror 我需要怎么办 我有台服务器 一直在闲置  看的这个计划我准备想加入 我如何加入

**Comment by XGHeaven** [comment]
这里是官方项目 https://github.com/bangbang93/openbmclapi ，可以直接看这个的，描述的挺详细的。
如果还不清楚的话，直接去棒棒的 bbs 上问就好了
